// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn-s2PqCk48wKD7f14S2n9SEDvGD8-yqA',
    appId: '1:257907654378:web:78f96ea8db66d12fdd6193',
    messagingSenderId: '257907654378',
    projectId: 'flutter-crud-tut',
    authDomain: 'flutter-crud-tut.firebaseapp.com',
    storageBucket: 'flutter-crud-tut.appspot.com',
    measurementId: 'G-YR464PEDFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCmWixwn636H8S-3UhaZZ_aR0W1ngtTug',
    appId: '1:257907654378:android:7b6c201e889abdb4dd6193',
    messagingSenderId: '257907654378',
    projectId: 'flutter-crud-tut',
    storageBucket: 'flutter-crud-tut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaHEOAu6EYUmAvWTluck5FhJ2OqmiEpwE',
    appId: '1:257907654378:ios:e59a74b5079a593add6193',
    messagingSenderId: '257907654378',
    projectId: 'flutter-crud-tut',
    storageBucket: 'flutter-crud-tut.appspot.com',
    iosClientId: '257907654378-iku8i4tckf5pu547p4s06umgosg7hiih.apps.googleusercontent.com',
    iosBundleId: 'com.flashminat0.firebaseflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaHEOAu6EYUmAvWTluck5FhJ2OqmiEpwE',
    appId: '1:257907654378:ios:e59a74b5079a593add6193',
    messagingSenderId: '257907654378',
    projectId: 'flutter-crud-tut',
    storageBucket: 'flutter-crud-tut.appspot.com',
    iosClientId: '257907654378-iku8i4tckf5pu547p4s06umgosg7hiih.apps.googleusercontent.com',
    iosBundleId: 'com.flashminat0.firebaseflutter',
  );
}
